# Generated by Django 3.0.5 on 2020-05-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='portfolio/images/thumbnail/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='portfolio/images/cover/')),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
